# Site settings
title: Machines... WTF?
email: bennor@gmail.com
description: ""
baseurl: ""
url: "http://machines.wtf"
twitter_username: kiwibennor
github_username:  bennor
stackoverflow_id: 14451

# Build settings
markdown: redcarpet

permalink: pretty
highlighter: rouge

sass:
#    style: :compressed